# Generated by Django 5.1.3 on 2025-06-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_blogposts_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', null=True, upload_to='images/', width_field='image_width'),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
