# Generated by Django 5.1.3 on 2025-06-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_blogposts_image_blogposts_image_height_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=300)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=350)),
                ('confirm_password', models.CharField(max_length=350)),
            ],
        ),
    ]
