# Generated by Django 5.1.3 on 2025-06-27 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogposts',
            name='comments',
            field=models.TextField(default='No comments'),
        ),
        migrations.AlterField(
            model_name='blogposts',
            name='image',
            field=models.ImageField(blank=True, default='bg2.jpg', height_field='image_height', null=True, upload_to='images/blog', width_field='image_width'),
        ),
    ]
